//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightProgram.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeightData()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int Id { get; set; }
        public string WarehouseName { get; set; }
        public string ScaleType { get; set; }
        public string VehiclePlateNumber { get; set; }
        public string CustomerName { get; set; }
        public string Goods { get; set; }
        public int Weight1 { get; set; }
        public int Weight2 { get; set; }
        public int WeightDifference { get; protected set; }
        public int ContainerCount { get; set; }
        public int ContainerWeightPerUnit { get; set; }
        public int ContainerTotalWeight { get; protected set; }
        public int NetGoodsWeight { get; protected set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
