//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightProgram.Data
{
    using SQLite.CodeFirst;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeightProgramModelContainer : DbContext
    {
        public WeightProgramModelContainer()
            : base("name=WeightProgramModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Ensure the database is created
            Database.SetInitializer(new WeightProgramModelInitializer(modelBuilder));
        }
    
        public virtual DbSet<WeightData> WeightDatum { get; set; }
    }
}
